# Necessary python packages

channels:
  - conda-forge

dependencies:
  - python=3.10.12                
  - robocorp-truststore=0.8.0     
  - pip=23.2.1                    
  - pip:
    - rpaframework==28.5.1        
    - robocorp==2.0.2             
    - robocorp-browser==2.3.3     
    - requests==2.31.0            
