name: Run Robocloud Fresh-News Process

on:
  push:
    branches:
      - master

jobs:
  run_process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Install RCC
        run: |
          curl -o rcc https://downloads.robocorp.com/rcc/releases/latest/linux64/rcc
          chmod +x rcc
          sudo mv rcc /usr/local/bin/rcc
          ./rcc configure credentials ${{ secrets.ROBOCORP_ACCESS_CREDENTIALS }} --account ${{ secrets.ROBOCORP_ACCOUNT_ID }}

      - name: Check if Robocloud Process Exists
        id: check_process
        run: |
          # Check if the process exists using rcc command
          if rcc process list | grep -q 'Placide_Ebongue'; then
            echo "name=exists::true" >> $GITHUB_OUTPUT
          else
            echo "name=exists::false" >> $GITHUB_OUTPUT
          fi

      - name: Create Robocloud Process if Not Exist
        if: steps.check_process.outputs.exists != 'true'
        run: |
          # Create the Robocloud process using rcc command
          rcc process create Placide_Ebongue

      - name: Run Robocloud Process
        env:
          ROBOCLOUD_API_KEY: ${{ secrets.ROBOCORP_API_KEY }}
        run: |
          # Trigger the Robocloud process using rcc command
          rcc run --process Placide_Ebongue
          # Capture the exit code of the previous command
          EXIT_CODE=$?
          # Provide feedback based on the exit code
          if [ $EXIT_CODE -eq 0 ]; then
            echo "Robocloud process completed successfully."
          else
            echo "Robocloud process failed with exit code $EXIT_CODE."
            exit $EXIT_CODE
          fi
